services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=pcfsAdmin
      - POSTGRES_PASSWORD=1pcFsDB!
      - POSTGRES_DB=pcdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql
  
volumes:
  postgres_db:
    driver: local
    name: postgres_db