// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PCFromScratch.Storage;

#nullable disable

namespace PCFromScratch.Migrations.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PCFromScratch.DBModels.Cooler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AmdSockets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("IntelSockets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Tdp")
                        .HasColumnType("integer");

                    b.Property<int>("Thickness")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coolers");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Packing")
                        .HasColumnType("integer");

                    b.Property<int>("RamFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("RamGen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tdp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tdp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.InternalDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InternalDrives");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.MotherboardRenamedForOmnissiah", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FormFactor")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RamFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("RamGeneration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RamSlots")
                        .HasColumnType("integer");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid?>("CpuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GpuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InternalDriveId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PsuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.HasIndex("InternalDriveId");

                    b.HasIndex("PsuId");

                    b.HasIndex("RamId");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Psu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FormFactor")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Modularity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<string>("PowerConnector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Psus");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.PsuConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PsuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PsuId");

                    b.ToTable("PsuConnector");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sticks")
                        .HasColumnType("integer");

                    b.Property<string>("Submodel")
                        .HasColumnType("text");

                    b.Property<float>("Voltage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Offer", b =>
                {
                    b.HasOne("PCFromScratch.DBModels.Cpu", null)
                        .WithMany("Offers")
                        .HasForeignKey("CpuId");

                    b.HasOne("PCFromScratch.DBModels.Gpu", null)
                        .WithMany("Offers")
                        .HasForeignKey("GpuId");

                    b.HasOne("PCFromScratch.DBModels.InternalDrive", null)
                        .WithMany("Offers")
                        .HasForeignKey("InternalDriveId");

                    b.HasOne("PCFromScratch.DBModels.Psu", null)
                        .WithMany("Offers")
                        .HasForeignKey("PsuId");

                    b.HasOne("PCFromScratch.DBModels.Ram", null)
                        .WithMany("Offers")
                        .HasForeignKey("RamId");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.PsuConnector", b =>
                {
                    b.HasOne("PCFromScratch.DBModels.Psu", null)
                        .WithMany("Connectors")
                        .HasForeignKey("PsuId");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Cpu", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Gpu", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.InternalDrive", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Psu", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PCFromScratch.DBModels.Ram", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
